course = "mooc-programming-25"

[exercises.part04-01_hello_visual_studio_code]
id = 272896
checksum = "914d5ec210005a85b2e209cb9fd3ecd1"

[exercises.part04-02_line]
id = 272891
checksum = "8f3e2a6d3b05017ddb353b9dd30e2916"

[exercises.part04-03_box_of_hashes]
id = 272928
checksum = "e2344900b9027bdeaf682e8317c05541"

[exercises.part04-04_square_of_hashes]
id = 272922
checksum = "d9d8d94bed3d8fbbafa457dc3269c51a"

[exercises.part04-05_square]
id = 272898
checksum = "1a9fdf76cc976fff65d9d3a00fa628ce"

[exercises.part04-06_triangle]
id = 272907
checksum = "0504289dc919e12378bec88f1e9f6b29"

[exercises.part04-07_shape]
id = 272921
checksum = "1d7b0fcc5dfca98367f4d35c00dabbe1"

[exercises.part04-08_spruce]
id = 272903
checksum = "0d85eb4acfc6e0188f644070453938cc"

[exercises.part04-09_greatest_number]
id = 272918
checksum = "0147b6c047ecd9ad57093aa7ec4cf7c4"

[exercises.part04-10_same_characters]
id = 272927
checksum = "c04232a3b25b64d7ff41bfc4c06c0642"

[exercises.part04-11_first_second_last]
id = 272909
checksum = "cd0025ff4dd5398dac11a58c46e114ad"

[exercises.part04-12_change_value_of_item]
id = 272919
checksum = "f132e43b40eb73c19903861d29d1ad88"

[exercises.part04-13_add_items_to_list]
id = 272926
checksum = "a8a3ff41e825a3c0e2e37e8211147da5"

[exercises.part04-14_addition_and_removal]
id = 272900
checksum = "eadc8c732eceae6d18e5d3b59baeabfc"

[exercises.part04-15_same_word_twice]
id = 272908
checksum = "fe47d1a7f039e320ab31315b54f41e25"

[exercises.part04-16_list_twice]
id = 272897
checksum = "a5b8cd167834ad1a40afde3cc49771ae"

[exercises.part04-17_length_of_list]
id = 272893
checksum = "93f01fb86508df8e1593faf8f75ddb75"

[exercises.part04-18_mean]
id = 272904
checksum = "f0466f1991de9c3db00789f82b9a1c17"

[exercises.part04-19_range_of_list]
id = 272902
checksum = "9bb5bd6457e892061b0e7f240cbf976e"

[exercises.part04-20_star_studded]
id = 272920
checksum = "4bb5153b48c4ef5bce600247ef8e366f"

[exercises.part04-21_negative_to_positive]
id = 272925
checksum = "239ad442ed484e0b5493180ff8c2f8d2"

[exercises.part04-22_list_of_stars]
id = 272901
checksum = "6d19315499f7a28b0b0889da3009a649"

[exercises.part04-23_anagrams]
id = 272924
checksum = "a53b024139b4793af0353f7536790425"

[exercises.part04-24_palindromes]
id = 272917
checksum = "42e787c35ab5153a3b153f0c373cb568"

[exercises.part04-25_sum_of_positives]
id = 272915
checksum = "1fe14ad751d7c70de452fae05886f914"

[exercises.part04-26_even_numbers]
id = 272913
checksum = "ff94e35d6b677477a2b1608f5e22589a"

[exercises.part04-27_sum_of_lists]
id = 272914
checksum = "8c3e1eb7e96e15b3c1c34cbc1c1a9c8c"

[exercises.part04-28_distinct_numbers]
id = 272906
checksum = "1b44f7e6ba7f4821566fc3cd764d75fd"

[exercises.part04-29_length_of_longest]
id = 272892
checksum = "f4ca93249d4d9b09252c6f047921f2d0"

[exercises.part04-30_shortest_in_list]
id = 272905
checksum = "9a218c3de1ccf93a87d1784f188e3d1b"

[exercises.part04-31_all_longest_in_list]
id = 272899
checksum = "43d2fd961e454effb6d300a8935647e9"

[exercises.part04-32_integers_to_strings]
id = 272894
checksum = "6d55e564701bef4da6bbac21b55fe2e5"

[exercises.part04-33_everything_reversed]
id = 272911
checksum = "573528e2be2c723f95960a10709a81d6"

[exercises.part04-34_most_common_character]
id = 272923
checksum = "5bf87be93e37895897f6927d8f1985c1"

[exercises.part04-35_no_vowels_allowed]
id = 272910
checksum = "3416dae84aea4bdbc7dcdca9b046f68f"

[exercises.part04-36_no_shouting_allowed]
id = 272912
checksum = "52158dc06dd9a7caf635528379c8e2a7"

[exercises.part04-37_neighbours_in_list]
id = 272916
checksum = "8be2192284a7742bd34787d73f717d2b"

[exercises.part04-38_grade_statistics]
id = 272895
checksum = "e1984de59716303252ba1ec8fa02d90e"

[exercises.part05-01_longest_string]
id = 272859
checksum = "1c8996da8c4581eceb4b51c9f1508fcf"

[exercises.part05-02_number_of_elements]
id = 272864
checksum = "2377dc13f035bffd59c69797449776e2"

[exercises.part05-03_go]
id = 272877
checksum = "f5bc87accd861e75b5d7483cd3b2b367"

[exercises.part05-04_sudoku_row]
id = 272860
checksum = "9536873ba7986058a7eb65ee648fdf9f"

[exercises.part05-05_sudoku_column]
id = 272868
checksum = "4204da9fb183be2862c2dc6f7388aa94"

[exercises.part05-06_sudoku_block]
id = 272867
checksum = "44fc1b6f95c5c95439cd3b0672501ad9"

[exercises.part05-07_sudoku_grid]
id = 272865
checksum = "b3e495e40530f0ce6f36f61f9189f7b2"

[exercises.part05-08_items_multiplied_by_two]
id = 272852
checksum = "9b77963e77f9034db0d39021f97b2f57"

[exercises.part05-09_remove_smallest]
id = 272862
checksum = "4d68b9c85e008a29f8fccd3f200af965"

[exercises.part05-10_sudoku_print_and_add]
id = 272878
checksum = "c13363c0c8ae25499ac3fcb29c68db93"

[exercises.part05-11_sudoku_add_to_copy]
id = 272873
checksum = "295d6053f4b7094174f0753d75326907"

[exercises.part05-12_tic_tac_toe]
id = 272856
checksum = "94b169b82fd3f8aa2cdf44d4b9d2a921"

[exercises.part05-13_transpose_matrix]
id = 272876
checksum = "c66720a19e1de6c84b589c8d6c96df51"

[exercises.part05-14_times_ten]
id = 272874
checksum = "56be9c0a1aac7a7439db7ea22620577d"

[exercises.part05-15_factorials]
id = 272861
checksum = "37990afadf65b45e3a69144a327ecb79"

[exercises.part05-16_histogram]
id = 272869
checksum = "f23d5493419cb22983d9a443bf78ad8d"

[exercises.part05-17_phone_book_v1]
id = 272854
checksum = "912044e0778ab65c260c0d769b475e36"

[exercises.part05-18_phone_book_v2]
id = 272857
checksum = "e270f6176a06d86817b88bf187a7031c"

[exercises.part05-19_invert_dictionary]
id = 272855
checksum = "fab1d4ce50545398faf500d73cc87f10"

[exercises.part05-20_numbers_spelled_out]
id = 272858
checksum = "f791c8571242587a2a3f521d7144435d"

[exercises.part05-21_movie_database]
id = 272872
checksum = "8ca07dc5c92259808cc8ddb1fbf436b7"

[exercises.part05-22_find_movies]
id = 272863
checksum = "2c2cbc2866d3efb4fb2aff33dda57e27"

[exercises.part05-23_create_tuple]
id = 272871
checksum = "0edb8e60ff8c5477eb4d9e057814532e"

[exercises.part05-24_oldest_person]
id = 272853
checksum = "ebd05a5fd779a3b4526456cd39e65a01"

[exercises.part05-25_older_people]
id = 272866
checksum = "e5b3b8e0e86020f48edf403686076536"

[exercises.part05-26_student_database]
id = 272875
checksum = "772044136c79bbccfea1035e6bf2a7d1"

[exercises.part05-27_letter_square]
id = 272870
checksum = "fdd20e535e47a623ee84e37724ad3693"

[exercises.part06-01_largest_number]
id = 272995
checksum = "1dfa2e7334b3d8162905aa09936d261a"

[exercises.part06-02_fruit_market]
id = 272981
checksum = "bf55476f14ca68c4c33d0344649a5c96"

[exercises.part06-03_matrix]
id = 272977
checksum = "bf9f8686347d7e7ef5edea699279d1f8"

[exercises.part06-04_course_grading_part_1]
id = 272980
checksum = "c538a7b29e21a1a1f62fa3b2ce7c6586"

[exercises.part06-05_course_grading_part_2]
id = 272992
checksum = "1c7f53542242b05d1fb543d0440a2635"

[exercises.part06-06_course_grading_part_3]
id = 272986
checksum = "748817b63a2d3e137f2a49c7f9fd0021"

[exercises.part06-07_spellchecker]
id = 272994
checksum = "ec58a96d7c384bfef9179f834f21f26d"

[exercises.part06-08_recipe_search]
id = 272987
checksum = "dc3e93a271f55d5168fa0b30aec437c6"

[exercises.part06-09_city_bikes]
id = 272990
checksum = "78dae11b3e75f8ef017ecf7f8dcb114a"

[exercises.part06-10_inscription]
id = 272985
checksum = "3226ccd3e0eda4c27a834cb9e5614a6e"

[exercises.part06-11_diary]
id = 272984
checksum = "ce6205a44c58bd429341d34408a9a7c7"

[exercises.part06-12_filtering_file_contents]
id = 272993
checksum = "74706a37234d394df3c884c1cfadf65c"

[exercises.part06-13_store_personal_data]
id = 272978
checksum = "02b62d2688636c0b194db22ef615f853"

[exercises.part06-14_course_grading_part_4]
id = 272979
checksum = "46181fedd194b0226d5ae01f1b5ab612"

[exercises.part06-15_word_search]
id = 272983
checksum = "3ca96ff6e6ee12c209c99bb4b623d0a8"

[exercises.part06-16_dictionary_file]
id = 272989
checksum = "e77bf7961847a89effa50bd41212baab"

[exercises.part06-17_read_input]
id = 272982
checksum = "0df738470f8991e0d7b6a0962475fe3e"

[exercises.part06-18_parameter_validation]
id = 272991
checksum = "1db239594ab7048945cbbab82ca9d99f"

[exercises.part06-19_incorrect_lottery_numbers]
id = 272988
checksum = "73356d105f9bb9686516e6c580a3ff54"

[exercises.part07-01_hypotenuse]
id = 273042
checksum = "429c8b4af0dd345de4e0e1290512bc2b"

[exercises.part07-02_special_characters]
id = 273032
checksum = "3d4056a574e537f0bfef38ca3461d1b2"

[exercises.part07-03_fractions]
id = 273029
checksum = "adb995503914c17bac145caea2f4c272"

[exercises.part07-04_lottery_numbers]
id = 273039
checksum = "f69497e068db01b7cf814c1c2e071195"

[exercises.part07-05_password_generator_part_1]
id = 273028
checksum = "b3082d7114ab0ac1ae4c594a45cc8a73"

[exercises.part07-06_password_generator_part_2]
id = 273044
checksum = "f1090f286ee1aa08f40174ef583a0b28"

[exercises.part07-07_dice_roller]
id = 273035
checksum = "c1e672584dc1335312b70a699ae326f2"

[exercises.part07-08_random_words]
id = 273038
checksum = "8f3bea4d53c1e649d95ba6d85e9ce447"

[exercises.part07-09_how_old]
id = 273040
checksum = "3ea947de751c0e73699f846dc7ec702e"

[exercises.part07-10_valid_pic]
id = 273037
checksum = "12602f7c8fc68a9caa5f284ded84eb3c"

[exercises.part07-11_screen_time]
id = 273027
checksum = "c9d2bfcbe85b17672d9a5ad400fcae1c"

[exercises.part07-12_json_files]
id = 273041
checksum = "602ce5f103ca15e9080044cedb158530"

[exercises.part07-13_course_statistics]
id = 273033
checksum = "a4a913755acb2c305206a3e4814eb67c"

[exercises.part07-14_who_cheated]
id = 273036
checksum = "de511315ea4f83657e952c24aab9b077"

[exercises.part07-15_who_cheated_2]
id = 273034
checksum = "47fd6ff3beabb3e5b59bcfef0d0bb34f"

[exercises.part07-16_spellchecker_2]
id = 273043
checksum = "2468cf899fb864cfdb25865a0d984bdc"

[exercises.part07-17_string_helper]
id = 273030
checksum = "78da558a98637c4d4f2fd9c8cbee0173"

[exercises.part07-18_own_programming_language]
id = 273031
checksum = "167f871586a0dfb963c75feed7721cf4"

[exercises.part08-01_smallest_average]
id = 272962
checksum = "21229e1a0b66cded2a08fd3323d0fec4"

[exercises.part08-02_row_sums]
id = 272975
checksum = "7e9f8a172a7280ec873ac7ae591fd9e1"

[exercises.part08-03_list_years]
id = 272968
checksum = "27d5975fceee610eb69f05b8f4bb7a12"

[exercises.part08-04_shopping_list]
id = 272976
checksum = "7924ae937ac5830dad8294b83ebd18c9"

[exercises.part08-05_book]
id = 272963
checksum = "198a5f9ac1bb9d2a3902d7f986d0c4ba"

[exercises.part08-06_three_classes]
id = 272965
checksum = "7de171b967813c36583493b1206a4dd0"

[exercises.part08-07_pet]
id = 272971
checksum = "a95b5d663aa3499566c277739fc77d4d"

[exercises.part08-08_older_book]
id = 272973
checksum = "1ae1e83cf09e6c354aa31daedafcc2fd"

[exercises.part08-09_books_of_genre]
id = 272972
checksum = "dd902b3ea42d582fe1dd1b2574864bc1"

[exercises.part08-10_decreasing_counter]
id = 272974
checksum = "5ab8cd65bd66ff3ca929ad3b85ff4b2c"

[exercises.part08-11_first_and_last_name]
id = 272970
checksum = "f8cc79ad63f893feb953b0a1509a4b0c"

[exercises.part08-12_number_stats]
id = 272969
checksum = "390b2e861d0a8a1b83d48fd7140686a6"

[exercises.part08-13_stopwatch]
id = 272966
checksum = "e79831b35f18a6701574e022ac2c2b91"

[exercises.part08-14_clock]
id = 272967
checksum = "f3bd0a1b4ba40728805a8baab5c1cfaa"

[exercises.part08-15_lunchcard]
id = 272961
checksum = "3eaffe42fb23a5e3be70c94f98b5e208"

[exercises.part08-16_series]
id = 272964
checksum = "65f7a10420e12753fd035bc342cf4a68"

[exercises.part09-01_fastest_car]
id = 272782
checksum = "20ed0109a93bfbc5beed267d3fa31a33"

[exercises.part09-02_passing_submissions]
id = 272794
checksum = "0ef5061328fc193363fd2e62db8670ea"

[exercises.part09-03_baby_centre]
id = 272780
checksum = "3a5b26153f04fea9a130192dea106749"

[exercises.part09-04_lunchcard_and_paymentterminal]
id = 272787
checksum = "eb3ac1d1b0bd060405ebb00d64a40be7"

[exercises.part09-05_comparing_properties]
id = 272792
checksum = "050f88b4cf8a98e6ce24cc002966096d"

[exercises.part09-06_pets]
id = 272789
checksum = "a9c8d607a8aef3dc6ce51b9e0b1e723d"

[exercises.part09-07_box_of_presents]
id = 272783
checksum = "be794896eefb4ebfe65301480045624c"

[exercises.part09-08_shortest_in_room]
id = 272790
checksum = "57b36fda7330e9d6376e1e4d1e9ec4da"

[exercises.part09-09_car]
id = 272781
checksum = "7e1092d8f0497fd1854f4fad8033431d"

[exercises.part09-10_recording]
id = 272784
checksum = "1111212e5e05f16ec2f51b3f71006c24"

[exercises.part09-11_weather_station]
id = 272786
checksum = "41740cb5841bc6650f4217ed016e5481"

[exercises.part09-12_service_charge]
id = 272785
checksum = "ab350c33a6a439499da01b3b00cd5718"

[exercises.part09-13_postcodes]
id = 272793
checksum = "fdf92024313a5c59fbbc7e132caa757f"

[exercises.part09-14_list_helper]
id = 272791
checksum = "cea6d7ce23cbc1029e5e1f533e83520e"

[exercises.part09-15_item_suitcase_hold]
id = 272788
checksum = "0592bc6bbd089b9d06836c8b6b66d222"

[exercises.part10-01_laptop_computer]
id = 272888
checksum = "7d3f79ad5f4160bb848e56dd3b2e5699"

[exercises.part10-02_game_museum]
id = 272879
checksum = "c3c4150a443d6ecb37f6f45908dcf3f2"

[exercises.part10-03_areas]
id = 272883
checksum = "e98415cf2ef8500d9b9258e185278855"

[exercises.part10-04_word_game]
id = 272881
checksum = "f83fecb4145982e2c7c845a9778a5dae"

[exercises.part10-05_supergroup]
id = 272880
checksum = "6dd38a1f66b90b6409bf5be463268bd5"

[exercises.part10-06_secret_magic_potion]
id = 272886
checksum = "d3fdeaee3b9e9264713c6270aa8297ca"

[exercises.part10-07_money]
id = 272884
checksum = "b9d389f21e9dc2b8f928e43a0e0b1c6a"

[exercises.part10-08_simple_date]
id = 272885
checksum = "18377e354734bf2b117211e7c4c6e043"

[exercises.part10-09_iterable_shopping_list]
id = 272889
checksum = "e86993b8c9e697bf1f427982b8b60aa0"

[exercises.part10-10_phone_book_v1]
id = 272890
checksum = "c4cbf8ba2711f794bf5894975cd7f1a2"

[exercises.part10-11_phone_book_v2]
id = 272887
checksum = "bc6e88bd247133fb7ac8394b3642448b"

[exercises.part10-12_course_records]
id = 272882
checksum = "ffa1abb57295e6f15469760b38f9aad5"

[exercises.part11-01_square_roots]
id = 272771
checksum = "4342e7ea3c572b693bc4a70b9de9afae"

[exercises.part11-02_rows_of_stars]
id = 272774
checksum = "1fa7140a5019a8e0801dc686a8288817"

[exercises.part11-03_best_exam_result]
id = 272769
checksum = "4f267581f9a52d3c2139a79864656647"

[exercises.part11-04_lengths]
id = 272765
checksum = "7cac65fe16a1f948b505439f656183ef"

[exercises.part11-05_remove_smaller_than]
id = 272770
checksum = "cf9fe2480665ff29d85824fc4c5a173f"

[exercises.part11-06_begin_with_vowel]
id = 272776
checksum = "4fdfc4e1c13243b9fdb2395f85c3497a"

[exercises.part11-07_lottery_numbers]
id = 272766
checksum = "f3aafbe375bc557bc6f4f73008218101"

[exercises.part11-08_filter_forbidden]
id = 272762
checksum = "2f094c09722a641d4dde0c722af92048"

[exercises.part11-09_products_in_shopping_list]
id = 272773
checksum = "f9dbf92ce2b3c913b8c67bebe935b3c5"

[exercises.part11-10_cheaper_properties]
id = 272764
checksum = "caf70c530d642e79c6c6e737c800f687"

[exercises.part11-11_lengths_of_strings]
id = 272772
checksum = "50205af4c0c5f8836a605715048df633"

[exercises.part11-12_most_common_words]
id = 272763
checksum = "f827a80e8e9d33e554a36690b8db7a5c"

[exercises.part11-13_add_numbers_to_list]
id = 272775
checksum = "6c1e32cd50b10a8257420692162515b6"

[exercises.part11-14_recursive_sum]
id = 272767
checksum = "6162ea8f23cfb8e577639f4e675bbacb"

[exercises.part11-15_balanced_brackets]
id = 272778
checksum = "0a96be190183e1c6a98a224a1ef52189"

[exercises.part11-16_greatest_node]
id = 272779
checksum = "7632558307ce949cf1266531dc9438e7"

[exercises.part11-17_bosses_and_subordinates]
id = 272761
checksum = "c1d7ecec44ba2d248f085e41ace936be"

[exercises.part11-18_order_book]
id = 272768
checksum = "01fde3297728f61ed4416d40cdd0a8fe"

[exercises.part11-19_order_book_application]
id = 272777
checksum = "b6d46431ea02a9664d2035d0b8029c14"

[exercises.part12-01_remaining_stock]
id = 272950
checksum = "65c5371873ae08f46885cebefa0e977a"

[exercises.part12-02_seasons]
id = 272953
checksum = "fc78319aeae2c284145a5f0e108b685b"

[exercises.part12-03_ratings]
id = 272957
checksum = "19ecd165af2322e513b2dfe82784bec2"

[exercises.part12-04_climbing_route]
id = 272948
checksum = "273df09084d2acd010334ae059967f62"

[exercises.part12-05_climbing_areas]
id = 272949
checksum = "bc95beab8c44f623104eb9aa26426cd5"

[exercises.part12-06_ballplayers]
id = 272960
checksum = "65e4b5afa5f7dd188ba3947d2a7255d9"

[exercises.part12-07_product_search]
id = 272954
checksum = "7f73987d9262f8807817c319d6ad8565"

[exercises.part12-08_even_numbers]
id = 272946
checksum = "953e925aad47db63b3814329a9b6d8d4"

[exercises.part12-09_prime_numbers]
id = 272951
checksum = "14168c20532cca6491b99e4ff476b189"

[exercises.part12-10_random_words]
id = 272959
checksum = "5509a6b128be600fa92c9aba19fe9a5a"

[exercises.part12-11_attempted_courses]
id = 272955
checksum = "1b3f4750598e5188da087067439e164e"

[exercises.part12-12_filtering_attempts]
id = 272956
checksum = "d58d86655b98cc5d94a1ae6641f3d4ea"

[exercises.part12-13_credits]
id = 272958
checksum = "8d81c094aa2fcab0e4ac6342671baf46"

[exercises.part12-14_regular_expressions]
id = 272947
checksum = "c6065f3dc9b8625db1ab2e189458657e"

[exercises.part12-15_hockey_statistics]
id = 272952
checksum = "0068f8f7edb4352e04905af2dc701483"

[exercises.part13-01_four_robots]
id = 272940
checksum = "61c76eccd16fb0984ac79a0dcc595273"

[exercises.part13-02_robots_row]
id = 272931
checksum = "351e997334e13c5ff0e833c0a6af7195"

[exercises.part13-03_hundred_robots]
id = 272936
checksum = "6aeede6c8918d2ae6f38e17b003f4ff1"

[exercises.part13-04_random_robots]
id = 272930
checksum = "ea6684a389807b53e85aa740b54a9efc"

[exercises.part13-05_vertical_movement]
id = 272943
checksum = "1afc9959ef4fad1580cef7a68b27dabc"

[exercises.part13-06_round_the_perimeter]
id = 272934
checksum = "b444ea39dd2553b5b2fc6f657b592c53"

[exercises.part13-07_two_robots]
id = 272938
checksum = "364dbbabcf14d3e5ce0c94d6c24b153d"

[exercises.part13-08_robot_circle]
id = 272933
checksum = "a91de025fd405507a95934c928560182"

[exercises.part13-09_bouncing_ball]
id = 272939
checksum = "2f76d0a824a7f6d28fac28249ac2e1a5"

[exercises.part13-10_robot_invasion]
id = 272932
checksum = "edb01ed2db07a3cb962d2fc24a7d7b40"

[exercises.part13-11_four_directions]
id = 272945
checksum = "17ab69c6a133c9ebcf2d08d9193a1ea1"

[exercises.part13-12_four_walls]
id = 272929
checksum = "d86b883c4c64960f7fd9cfba362f0187"

[exercises.part13-13_two_players]
id = 272941
checksum = "b6ae3bcc9d70b4acd6d525c13faea91e"

[exercises.part13-14_robot_and_mouse]
id = 272935
checksum = "656f51b5eb0c28dcfd6dbce74a3fa115"

[exercises.part13-15_robot_location]
id = 272942
checksum = "4c748a9cd51b46630e20041a31f03f71"

[exercises.part13-16_clock]
id = 272937
checksum = "628befa4aba8c8771f6d8d1ac1d33e5d"

[exercises.part13-17_asteroids]
id = 272944
checksum = "50570f044e4587f37f18afdc09d532fb"
